import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import contentfulClient from '@/client/ContentfulClient'
import { mapCourses } from '@/utils/CourseUtils'
import { Course } from '@/types/Course'
import CoursesContainer from '@/components/Courses/CoursesContainer'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const contentfulCourses:any = await contentfulClient.getEntries({
    content_type: "course",
  }).then((res) => res.items)
  const courses:Course[] = mapCourses(contentfulCourses);
  return { props: { courses } };
}

function Courses(props: { courses:Course[] }) {
  console.log(props.courses);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Header />
        <div className="test">
          <CoursesContainer courses={props.courses} />
          <div className="sidebar"></div>
        </div>
      </main>
    </>
  )
}

export default Courses;