import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import contentfulClient from '@/client/ContentfulClient'
import { mapBlogs } from '@/utils/BlogUtils'
import { Blog } from '@/types/Blog'
import CoursesContainer from '@/components/Courses/CoursesContainer'
import { Course } from '@/types/Course'
import { mapCourses } from '@/utils/CourseUtils'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  // const contentfulBlog: any = await contentfulClient.getEntries({
  //   content_type: "blog",
  // }).then((res) => res.items)
  // console.log("================", contentfulBlog);
  // const blogs: Blog[] = mapBlogs(contentfulBlog);
  // const projects = mapBlog(contentfulBlog);
  const contentfulCourses:any = await contentfulClient.getEntries({
    content_type: "course",
  }).then((res) => res.items)
  const courses:Course[] = mapCourses(contentfulCourses);
  return { props: { courses } };
}

export default function Home(props: { courses: Course[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Header />
        <div className="test">
          <CoursesContainer courses={props.courses} />
        </div>
      </main>
    </>
  )
}
