import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import contentfulClient from '@/client/ContentfulClient'
import CoursesContainer from '@/components/Courses/CoursesContainer'
import { Course } from '@/types/Course'
import { mapCourses } from '@/utils/CourseUtils'
import Link from 'next/link'
import Image from 'next/image'
import TrainingParagraph from '@/components/TrainingParagraph/TrainingParagraph'
import Choq from '@/components/Choq/Choq'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const training: any = await contentfulClient.getEntries({
    content_type: "trainigProgram",
  }).then((res) => res.items[0].fields)
  const contentfulCourses: any = await contentfulClient.getEntries({
    content_type: "course",
  }).then((res) => res.items)
  const courses: Course[] = mapCourses(contentfulCourses);
  const about: any = await contentfulClient.getEntries({
    content_type: "aboutMe",
  }).then((res) => res.items)

  return { props: { courses, about, training } };
}

export default function Home(props: { courses: Course[], about: any, training: any }) {
  console.log("================", props.training);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Header state={true} training={true} />

        <TrainingParagraph text={props.training} />

        <CoursesContainer courses={props.courses} about={props.about[0]} />

        <Choq />

      </main>
    </>
  )
}
